name: QA Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  QAFlow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang-format
          version: 1.0

      # Run style check for STM32
      - name: Run style check for STM32
        uses: ./.github/actions/style
        with:
          path: STM32

      # Run documentation check for STM32
      - name: Run documentation check for STM32
        uses: ./.github/actions/document
        with:
          path: STM32

      # Build STM32 project using PlatformIO
      - name: Build STM32 Project
        uses: ./.github/actions/build
        with:
          path: STM32
