# Run style check for STM32
- name: Run style check for STM32
  run: |
    if [ -d "STM32/src" ]; then
      cd STM32
      ../../.github/actions/style/action.yml --path src
    else
      echo "STM32/src directory not found."
      exit 1
    fi

# Run style check for LPC1769
- name: Run style check for LPC1769
  run: |
    if [ -d "LPC1769/src" ]; then
      cd LPC1769
      ../../.github/actions/style/action.yml --path src
    else
      echo "LPC1769/src directory not found."
      exit 1
    fi
