name: QA Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  QAFlow:
    runs-on: ubuntu-latest

    steps:
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: "13.3.Rel1"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen gcovr lcov cppcheck graphviz clang-format
          version: 1.0

      # Run style check for STM32
      - name: Run style check for STM32
        run: ./.github/actions/style/action.yml --path STM32
        shell: bash

      # Run style check for LPC1769
      - name: Run style check for LPC1769
        run: ./.github/actions/style/action.yml --path LPC1769
        shell: bash

      # Run documentation check for STM32
      - name: Run documentation check for STM32
        run: ./.github/actions/document/action.yml --path STM32
        shell: bash

      # Run documentation check for LPC1769
      - name: Run documentation check for LPC1769
        run: ./.github/actions/document/action.yml --path LPC1769
        shell: bash

      # Build project for STM32
      - name: Build STM32 project
        run: ./.github/actions/build/action.yml --path STM32
        shell: bash

      # Build project for LPC1769
      - name: Build LPC1769 project
        run: ./.github/actions/build/action.yml --path LPC1769
        shell: bash
