name: QA Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  QAFlow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: "13.3.Rel1"

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen gcovr lcov cppcheck graphviz clang-format
          version: 1.0

      # Run style check for STM32
      - name: Run style check for STM32
        run: |
          if [ -d "STM32/src" ]; then
            cd STM32
            ./github/actions/style --path src
          else
            echo "STM32/src directory not found."
            exit 1
          fi

      # Run style check for LPC1769
      - name: Run style check for LPC1769
        run: |
          if [ -d "LPC1769/src" ]; then
            cd LPC1769
            ./github/actions/style --path src
          else
            echo "LPC1769/src directory not found."
            exit 1
          fi

      # Run documentation check for STM32
      - name: Run documentation check for STM32
        run: |
          if [ -d "STM32/src" ]; then
            cd STM32
            ./github/actions/document --path src
          else
            echo "STM32/src directory not found."
            exit 1
          fi

      # Run documentation check for LPC1769
      - name: Run documentation check for LPC1769
        run: |
          if [ -d "LPC1769/src" ]; then
            cd LPC1769
            ./github/actions/document --path src
          else
            echo "LPC1769/src directory not found."
            exit 1
          fi

      # Build project for STM32
      - name: Build project for STM32
        run: |
          if [ -d "STM32/src" ]; then
            cd STM32
            ./github/actions/build --path src
          else
            echo "STM32/src directory not found."
            exit 1
          fi

      # Build project for LPC1769
      - name: Build project for LPC1769
        run: |
          if [ -d "LPC1769/src" ]; then
            cd LPC1769
            ./github/actions/build --path src
          else
            echo "LPC1769/src directory not found."
            exit 1
          fi
